name: Day-12
on:
  workflow_dispatch:
  push:
    paths:
      - "**12*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amplium/git-crypt-action@master
        with:
          key_encoded: ${{ secrets.GIT_CRYPT_KEY }}
      - uses: php-actions/composer@v6
      - name: Create Custom php.ini
        run: |
          cp $(php --ini | grep "Loaded Configuration File" | sed -e "s|.*:\s*||") ./php.ini
          echo "xdebug.max_nesting_level=512" >> ./php.ini
          echo "xdebug.max_stack_frames=512" >> ./php.ini
      - name: Run with Custom php.ini
        run: php -c ./php.ini src/main.php 12 -b

