name: Day-12
on:
  workflow_dispatch:
  push:
    paths:
      - "**12*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amplium/git-crypt-action@master
        with:
          key_encoded: ${{ secrets.GIT_CRYPT_KEY }}
      - uses: php-actions/composer@v6
      - name: Increase Xdebug Limits
        run: |
          echo "xdebug.max_nesting_level=512" >> $(php --ini | grep "Loaded Configuration File" | sed -e "s|.*:\s*||")
          echo "xdebug.max_stack_frames=512" >> $(php --ini | grep "Loaded Configuration File" | sed -e "s|.*:\s*||")
          php --ini # Verify changes
      - name: Run
        run: php src/main.php 12 -b

